// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logos/CipherHelix.tsx": () => import("../components/mockups/logos/CipherHelix.tsx"),
  "./components/mockups/logos/OrbitalLock.tsx": () => import("../components/mockups/logos/OrbitalLock.tsx"),
  "./components/mockups/logos/QuantumKey.tsx": () => import("../components/mockups/logos/QuantumKey.tsx"),
  "./components/mockups/logos/QuantumShield.tsx": () => import("../components/mockups/logos/QuantumShield.tsx")
};
